### ISSUE TITLE
[BUG] Does not work with the 2023.5.2 release.

### ISSUE THREAD

**Issue by decuple-dream** [CoreyD97/BurpCustomizer#20]
**Describe the bug**
Recently, BurpSuite announced the release of 2023.5.2. However, using the Customizer with this version results in the following error.

<img width="807" alt="스크린샷 2023-06-05 오후 7 14 03" src="https://github.com/CoreyD97/BurpCustomizer/assets/67303734/9188d7c1-af23-469b-9608-2dba4807fe9a">

**Comment by Saduff** [comment]
Same here. I would like to add that this error only shows up once when the extension is loaded and at least in my case the theme is still applied despite the error message.

**Comment by CoreyD97** [comment]
Are you still having this issue? It seems to be working fine on the latest early access release for me.

**Comment by decuple-dream** [comment]
<img width="958" alt="스크린샷 2023-07-03 오후 4 41 37" src="https://github.com/CoreyD97/BurpCustomizer/assets/67303734/3f63cd86-cf7c-4394-914c-0c0f126830ff">

@CoreyD97, It's still the same.

**Comment by Saduff** [comment]
I found that the version in the BApp Store is v1.0.2 for some reason, even though v1.0.3 was released back in 2021. :disappointed: 
So I installed the latest v1.0.3 release from GitHub. However, the issue is still there with v1.0.3 and Burp v2023.7 EA.

Here's the full stacktrace:
```java
Could not load theme.
java.lang.NullPointerException: Cannot invoke "java.awt.Component.getParent()" because "<local1>" is null
	at burp.Zn4i.updateUI(Unknown Source)
	at java.desktop/javax.swing.SwingUtilities.updateComponentTreeUI0(SwingUtilities.java:1363)
	at java.desktop/javax.swing.SwingUtilities.updateComponentTreeUI0(SwingUtilities.java:1378)
	at java.desktop/javax.swing.SwingUtilities.updateComponentTreeUI0(SwingUtilities.java:1378)
	at java.desktop/javax.swing.SwingUtilities.updateComponentTreeUI0(SwingUtilities.java:1378)
	at java.desktop/javax.swing.SwingUtilities.updateComponentTreeUI0(SwingUtilities.java:1378)
	at java.desktop/javax.swing.SwingUtilities.updateComponentTreeUI0(SwingUtilities.java:1378)
	at java.desktop/javax.swing.SwingUtilities.updateComponentTreeUI0(SwingUtilities.java:1378)
	at java.desktop/javax.swing.SwingUtilities.updateComponentTreeUI0(SwingUtilities.java:1378)
	at java.desktop/javax.swing.SwingUtilities.updateComponentTreeUI0(SwingUtilities.java:1378)
	at java.desktop/javax.swing.SwingUtilities.updateComponentTreeUI0(SwingUtilities.java:1378)
	at java.desktop/javax.swing.SwingUtilities.updateComponentTreeUI0(SwingUtilities.java:1378)
	at java.desktop/javax.swing.SwingUtilities.updateComponentTreeUI0(SwingUtilities.java:1378)
	at java.desktop/javax.swing.SwingUtilities.updateComponentTreeUI0(SwingUtilities.java:1378)
	at java.desktop/javax.swing.SwingUtilities.updateComponentTreeUI0(SwingUtilities.java:1378)
	at java.desktop/javax.swing.SwingUtilities.updateComponentTreeUI0(SwingUtilities.java:1378)
	at java.desktop/javax.swing.SwingUtilities.updateComponentTreeUI0(SwingUtilities.java:1378)
	at java.desktop/javax.swing.SwingUtilities.updateComponentTreeUI0(SwingUtilities.java:1378)
	at java.desktop/javax.swing.SwingUtilities.updateComponentTreeUI0(SwingUtilities.java:1378)
	at java.desktop/javax.swing.SwingUtilities.updateComponentTreeUI(SwingUtilities.java:1354)
	at com.formdev.flatlaf.FlatLaf.updateUI(FlatLaf.java:1055)
	at com.coreyd97.burpcustomizer.BurpCustomizer.setTheme(BurpCustomizer.java:139)
	at com.coreyd97.burpcustomizer.CustomizerPanel$2.lambda$actionPerformed$0(CustomizerPanel.java:192)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:771)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:741)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

```

**Comment by sa7mon** [comment]
Additional data point: in `v2023.6.2`, this error comes up when applying a theme. The theme does work perfectly find but the error gets thrown.

```java
Could not load theme.
java.lang.NullPointerException: Cannot invoke "java.awt.Component.getParent()" because "<local1>" is null
	at burp.Zbq4.updateUI(Unknown Source)
	at java.desktop/javax.swing.SwingUtilities.updateComponentTreeUI0(SwingUtilities.java:1363)
	at java.desktop/javax.swing.SwingUtilities.updateComponentTreeUI0(SwingUtilities.java:1378)
	at java.desktop/javax.swing.SwingUtilities.updateComponentTreeUI0(SwingUtilities.java:1378)
	at java.desktop/javax.swing.SwingUtilities.updateComponentTreeUI0(SwingUtilities.java:1378)
	at java.desktop/javax.swing.SwingUtilities.updateComponentTreeUI0(SwingUtilities.java:1378)
	at java.desktop/javax.swing.SwingUtilities.updateComponentTreeUI0(SwingUtilities.java:1378)
	at java.desktop/javax.swing.SwingUtilities.updateComponentTreeUI0(SwingUtilities.java:1378)
	at java.desktop/javax.swing.SwingUtilities.updateComponentTreeUI0(SwingUtilities.java:1378)
	at java.desktop/javax.swing.SwingUtilities.updateComponentTreeUI0(SwingUtilities.java:1378)
	at java.desktop/javax.swing.SwingUtilities.updateComponentTreeUI0(SwingUtilities.java:1378)
	at java.desktop/javax.swing.SwingUtilities.updateComponentTreeUI0(SwingUtilities.java:1378)
	at java.desktop/javax.swing.SwingUtilities.updateComponentTreeUI0(SwingUtilities.java:1378)
	at java.desktop/javax.swing.SwingUtilities.updateComponentTreeUI0(SwingUtilities.java:1378)
	at java.desktop/javax.swing.SwingUtilities.updateComponentTreeUI0(SwingUtilities.java:1378)
	at java.desktop/javax.swing.SwingUtilities.updateComponentTreeUI0(SwingUtilities.java:1378)
	at java.desktop/javax.swing.SwingUtilities.updateComponentTreeUI0(SwingUtilities.java:1378)
	at java.desktop/javax.swing.SwingUtilities.updateComponentTreeUI0(SwingUtilities.java:1378)
	at java.desktop/javax.swing.SwingUtilities.updateComponentTreeUI0(SwingUtilities.java:1378)
	at java.desktop/javax.swing.SwingUtilities.updateComponentTreeUI(SwingUtilities.java:1354)
	at com.formdev.flatlaf.FlatLaf.updateUI(FlatLaf.java:1055)
	at com.coreyd97.burpcustomizer.BurpCustomizer.setTheme(BurpCustomizer.java:139)
	at com.coreyd97.burpcustomizer.CustomizerPanel$2.lambda$actionPerformed$0(CustomizerPanel.java:192)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by MrADus** [comment]
![image](https://github.com/CoreyD97/BurpCustomizer/assets/96512594/4df190f6-9d63-4268-bac0-a3aa9d430d09)
why is that?

**Comment by Saduff** [comment]
The issue randomly disappeared for me with [Burp v2023.10.2 EA](https://portswigger.net/burp/releases/professional-community-2023-10-2), i.e. I don't get the error message anymore. I haven't changed any Burp extensions in the meantime.

> Additionally, the theme is not loaded automatically on startup anymore in Burp v2023.7 EA.

This seems to work again as well. However, there's some weird issue where the theme does not look quite right (colors are off, some buttons have a grey background etc) until applying the theme again manually with the Apply button.
